### ISSUE TITLE
this thing is too bad.

### ISSUE THREAD

**Issue by vldr** [EpikPhailure/flamin-hot-cheetos#1]
aimboat doesnt work. should probably fix dat.

**Comment by EpikPhailure** [comment]
learn to update the project yeah, not my fault if you don't have a clue

**Comment by vldr** [comment]
nothing to update, your aimbot sucks.

**Comment by EpikPhailure** [comment]
doesn't work and sucking are two different things
you're obviously an autismo xDDDD

**Comment by vldr** [comment]
Lol, but seriously, the offsets seem to be up to date, just the aimbot faces up when locking onto someone.

**Comment by EpikPhailure** [comment]
I pushed an update a little while ago
