### ISSUE TITLE
Crashing while entering the game.

### ISSUE THREAD

**Issue by confirmed12** [EpikPhailure/flamin-hot-cheetos#3]
Compiled in release mode 86x everything works fine but once you join a match the game crashes. Any way to fix this?

**Comment by EpikPhailure** [comment]
I don't know the issue, but if you figure it out feel free to create a pull request. It works for me and some others though.

**Comment by confirmed12** [comment]
Can't find anything either.

**Comment by ekifox** [comment]
+1
The game crashes after loading the map, even if you turn off all the settings

**Comment by EpikPhailure** [comment]
Hey, made a bunch of changes today and I might have finally figured it out. Pull the updates and let me know how it is.

**Comment by ekifox** [comment]
not fixed...(((

**Comment by EpikPhailure** [comment]
Try commenting out all the hooks in Hooks.cpp and try injecting. If it doesnt crash then slowly re-enable each each one by one until the game crashes tell me the hooked function that causes the crash.
